[[ algorithms ]]
    name = "MinScore"
    title = "MinScore50"

    [ algorithms.options ]
        min_score = 50

#[[ algorithms ]]
#    name = "MinScore"
#    title = "MinScore100"
#
#    [ algorithms.options ]
#        min_score = 100
#
#[[ algorithms ]]
#    name = "MinScore"
#    title = "MinScore200"
#
#    [ algorithms.options ]
#        min_score = 200
#
#[[ algorithms ]]
#    name = "MinScore"
#    title = "MinScore300"
#
#    [ algorithms.options ]
#        min_score = 300
#
#[[ algorithms ]]
#    name = "MinScore"
#    title = "MinScore400"
#
#    [ algorithms.options ]
#        min_score = 400
#
#[[ algorithms ]]
#    name = "MinScore"
#    title = "MinScore500"
#
#    [ algorithms.options ]
#        min_score = 500
